[project]
name = "samaa"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Sama Abuolba", email = "abuolbas@mcmaster.ca" }
]
requires-python = ">=3.13"
dependencies = [
    "numpy>=2.5.3",
    "rosa-starter",
    "streamlit>=1.65.0",
]

[build-system]
requires = ["uv_build>=0.12.20,<0.13.0"]
build-backend = "uv_build"

[tool.uv]
package = false

[tool.uv.sources]
rosa-starter = { url = "https://github.com/zhouy185/rosa-starter/archive/refs/heads/main.zip" }
